config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :users
  # resources :campaigns
  resources :blogs do 
    resources :campaigns
  end
  root 'blogs#index'

  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :campaigns
  has_one_attached :img
  has_many :blog_tags
  has_many :tags, through: :blog_tags
end

app/controllers/blogs_controller.rb
# coding: utf-8
# frozen_string_literal: true

class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]
  authorize_resource

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show; end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
    end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    if params[:change_body]
      ps = params.require(:blog).permit(:body)
    else
      ps = blog_params
    end
    respond_to do |format|
      if @blog.update(ps)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
    p @blog.img
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :body, :image, :image_cache, :remove_image, :img, tag_ids: [])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

<div class="form-group">
  <%= form.select :tag_ids, Tag.all.collect {|x| [x.title, x.id]}, {}, {multiple: true,class: 'form-control'}  %>
</div>


  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body , class: 'form-control'%>
  </div>
  <div class="actions">
    <%= form.submit "ボディ",name: :change_body ,class: 'btn btn-success' %>
  </div>


  <!-- 追加箇所 開始 -->
  <div class="form-group">
    <% if @blog.image? %>
      <div class="thumbnail">
        <%= image_tag @blog.image.url %>
      </div>
    <% end %><br>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
    <div class="input-group">
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="form-group">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @blog.persisted? && @blog.image? %>
      <label>
        <%= form.check_box :remove_image %>
        画像を削除
      </label>
    <% end %>
  </div>
  <!-- 追加箇所 終了 -->

  <div class="form-group">
    <% if @blog.img.attached? %>
      <div class="thumbnail">
        <%= image_tag @blog.img %>
      </div>
    <% end %><br>
    <%= form.label :img %><br>
    <%= form.file_field :img %>
  </div>


  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to t(:show), @blog,class: "btn btn-sm btn-primary",style: "color:#fff" %> 
<%= link_to t(:back), blogs_path,class: "btn btn-sm btn-primary",style: "color:#fff" %>

app/views/blogs/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<h1><%= t(:blogs) %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%= t(:title) %></th>
      <th><%= t(:body) %></th>
      <th>タグ</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><% blog.tags.each do |t|  %>
          <%= t.title%>
        <% end %></td>              
        <td><%= link_to t(:show), blog ,class: "btn btn-sm btn-primary",style: "color:#fff" %></td>
        <td><%= link_to t(:edit), edit_blog_path(blog) ,class: "btn btn-sm btn-primary",style: "color:#fff"%></td>
        <td><%= link_to t(:delete), blog, method: :delete, data: { confirm: t(:confirm) } ,class: "btn btn-danger btn-sm",style: "color:#fff"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t(:new), new_blog_path,class: "btn btn-primary",style: "color:#fff" %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>
<!-- 追加箇所 開始 -->

<p>
  <strong>Image:</strong>
  <% if @blog.image? %>
    <div class="thumbnail">
      <%= image_tag @blog.image.url %>
    </div>
  <% end %>
</p>
<!-- 追加箇所 終了 -->
<p>
  <strong>img:</strong>
  <% if @blog.img.attached? %>
    <div class="thumbnail">
      <%= image_tag @blog.img %>
    </div>
  <% end %>
</p>

<%= link_to t(:edit), edit_blog_path(@blog),class: "btn btn-sm btn-primary",style: "color:#fff" %> 
<%= link_to t(:back), blogs_path,class: "btn btn-sm btn-primary",style: "color:#fff" %>