config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :users
  # resources :campaigns
  resources :blogs do 
    resources :campaigns
  end
  root 'blogs#index'

  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :blog
end

app/controllers/campaigns_controller.rb
# frozen_string_literal: true

class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[show edit update destroy]
  authorize_resource

  # GET /campaigns
  # GET /campaigns.json
  def index
    # @campaigns = Campaign.all
    @campaigns = Campaign.where(blog_id: params[:blog_id])
    p @campaigns
    
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    #     SampleMailer.send_when_create.deliver
  end

  # GET /campaigns/new
  def new
    blog = Blog.find(params[:blog_id])
    @campaign = blog.campaigns.new
    #    @campaign = Campaign.new
    #    if params[:blog_id]
    #      @campaign.blog_id = params[:blog_id]
    #    end
  end

  # GET /campaigns/1/edit
  def edit; end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)
    respond_to do |format|
      if @campaign.save
        # SampleMailer.send_when_create.deliver
        MyJob.perform_later
        format.html { redirect_to blog_campaign_path(id: @campaign.id, blog_id: @campaign.blog_id), notice: 'Campaign was successfully created.' }
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to blog_campaign_path(id: @campaign.id, blog_id: @campaign.blog_id), notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    blog_id = @campaign.blog_id
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to blog_campaigns_path(blog_id: blog_id), notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def campaign_params
    params.require(:campaign).permit(:name, :blog_id)
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, local: true, url: path) do |form| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<!--
  <div class="field">
    <%= form.label :blog_id %>
    <%= form.text_field :blog_id %>
  </div>
-->
  <%= form.hidden_field :blog_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign, path: blog_campaign_path %>

<%= link_to 'Show', blog_campaign_path(id: @campaign.id) %> |
<%= link_to 'Back', blog_campaigns_path(blog_id: @campaign.blog_id) %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Blog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.name %></td>
        <td><%= campaign.blog.id %></td>
        <td>
          <%= link_to t(:show), blog_campaign_path(id: campaign.id) %>
        </td>
        <td>
          <% if can? :update, current_user %>
          <%= link_to t(:edit), edit_blog_campaign_path(campaign.blog_id,campaign.id) %>
          <% end %>
        </td>
        <td>
          <% if can? :destroy, current_user %>
          <%= link_to t(:delete), blog_campaign_path(id: campaign.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_blog_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign, path: blog_campaigns_path %>

<%= link_to t(:back), blog_campaigns_path(blog_id: @campaign.blog_id),class: "btn btn-primary",style: "color:#fff" %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @campaign.name %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @campaign.blog %>
</p>

<%= link_to 'Edit', edit_blog_campaign_path(@campaign.blog_id,@campaign.id),class: "btn btn-primary",style: "color:#fff" %>
<%= link_to 'Back', blog_campaigns_path(blog_id: @campaign.blog_id),class: "btn btn-primary",style: "color:#fff" %>